---
- name: reload systemd
  systemd:
    daemon_reload: yes
  when: not is_docker

- name: Restart the application systemd unit
  service:
    name: "{{ nodejs_app_name }}"
    state: restarted
  when: (not is_docker) and (nodejs_app_start_script)
